### ISSUE TITLE
Modal-pop-up-days

### ISSUE THREAD

**Issue by theravenmasque** [CodeITLab/fit_track_frontend_app#4]
Button for day card creation

**Comment by kristijanfistrek** [comment]
našao sam ovaj tutorial za modal: https://medium.com/@romanvinnick/vue3-composition-api-creating-a-reusable-modal-component-with-outside-click-handling-43e830d289c1 ljepim ovdje jer će nam dobro doći :D

**Comment by kristijanfistrek** [comment]
@theravenmasque 

https://bootstrap-vue.org/docs/components/modal

Možemo zamijeniti ovaj gore custom reusable modal samo sa boostrapovim :D mislim da će nam ovo puno čišće i lakše biti.
